version: "2.1"
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: monumenten

  importer:
    image: build.datapunt.amsterdam.nl:5000/datapunt/monumenten:${ENVIRONMENT}
    links:
      - database
    environment:
      OBJECTSTORE_PASSWORD:
      DATABASE_NAME: monumenten
      DATABASE_USER: monumenten
      DATABASE_PASSWORD: insecure
      DATABASE_HOST_OVERRIDE: database
      DATABASE_PORT_OVERRIDE: 5432
      DATAPUNT_API_URL: ${DATAPUNT_API_URL:-https://api.datapunt.amsterdam.nl/}

    command: >
      bash -c "./docker-wait.sh \
              && python manage.py migrate \
              && python manage.py run_import"

  db-backup:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    links:
      - database:db
    volumes:
      - ./backups:/tmp/backups
    command: >
      bash -c "echo db:5432:monumenten:monumenten:insecure > ~/.pgpass \
              && chmod 600 ~/.pgpass \
              && pg_dump --clean \
                          -Fc \
                          -t monumenten* \
                          -t geo*  \
                          -t django_migrations  \
                          -t django_site \
                          -T auth*    \
                          -U monumenten \
                          -h db -p 5432 \
                          monumenten > /tmp/backups/database.dump"
